# Generated by Django 2.2.3 on 2019-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='game name')),
                ('image', models.ImageField(blank=True, upload_to='product_image')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('place', models.CharField(max_length=64, verbose_name='place')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='place')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
            ],
        ),
    ]
