# Generated by Django 2.2.3 on 2019-09-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplegame',
            name='name',
            field=models.CharField(max_length=32, verbose_name='game name'),
        ),
        migrations.CreateModel(
            name='SampleCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=32, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='phone')),
                ('command_name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('members', models.IntegerField(verbose_name='members count')),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('active', models.BooleanField(default=False, verbose_name='is active')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SampleGame', verbose_name='game')),
            ],
        ),
    ]
