# Generated by Django 2.2.3 on 2019-09-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190917_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplecommand',
            old_name='command_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='samplecommand',
            name='game',
        ),
        migrations.RemoveField(
            model_name='samplecommand',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='samplecommand',
            name='members',
        ),
        migrations.RemoveField(
            model_name='samplecommand',
            name='phone',
        ),
        migrations.CreateModel(
            name='ComingRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=32, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='phone')),
                ('command_name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('members', models.IntegerField(verbose_name='members count')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SampleGame', verbose_name='game')),
            ],
        ),
    ]
