# Generated by Django 2.2.3 on 2019-09-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190917_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleQwiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='comingrequests',
            name='capitan_name',
            field=models.CharField(default='ivan', max_length=32, verbose_name='имя капитана'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comingrequests',
            name='command_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='название команды'),
        ),
        migrations.AlterField(
            model_name='comingrequests',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SampleGame', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comingrequests',
            name='members',
            field=models.CharField(choices=[(1, '1 участник'), (2, '2 участника'), (3, '3 участника'), (4, '4 участника'), (5, '5 участников'), (6, '6 участников')], max_length=16, verbose_name='количество участников'),
        ),
        migrations.AlterField(
            model_name='comingrequests',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='samplegame',
            name='date',
            field=models.DateField(verbose_name='date: xx.xx.xxxx'),
        ),
        migrations.AlterField(
            model_name='samplegame',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='samplegame',
            name='time',
            field=models.TimeField(verbose_name='time: xx:xx'),
        ),
        migrations.CreateModel(
            name='Qwestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qwestion', models.CharField(max_length=128, verbose_name='qwestion')),
                ('answer_a', models.CharField(max_length=64, verbose_name='answer_a')),
                ('answer_b', models.CharField(max_length=64, verbose_name='answer_b')),
                ('answer_c', models.CharField(max_length=64, verbose_name='answer_c')),
                ('answer_d', models.CharField(max_length=64, verbose_name='answer_d')),
                ('true_answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, verbose_name='answer_d')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SampleQwiz', verbose_name='theme')),
            ],
        ),
    ]
