# Generated by Django 2.2.3 on 2019-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190928_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingrequests',
            name='members',
            field=models.CharField(choices=[('1', '1 участник'), ('2', '2 участника'), ('3', '3 участника'), ('4', '4 участника'), ('5', '5 участников'), ('6', '6 участников')], max_length=16, verbose_name='количество участников'),
        ),
    ]
