# Generated by Django 2.2.3 on 2019-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190928_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplegame',
            name='active',
        ),
        migrations.AddField(
            model_name='sampleqwiz',
            name='active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
