# Generated by Django 2.2.3 on 2019-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190929_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegame',
            name='image_big',
            field=models.ImageField(blank=True, upload_to='image big'),
        ),
        migrations.AlterField(
            model_name='samplegame',
            name='image',
            field=models.ImageField(blank=True, upload_to='image min'),
        ),
    ]
