# Generated by Django 2.2.3 on 2019-10-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190930_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qwestions',
            name='true_answer',
        ),
        migrations.AddField(
            model_name='qwestions',
            name='point_a',
            field=models.IntegerField(default=0, verbose_name='points_a'),
        ),
        migrations.AddField(
            model_name='qwestions',
            name='point_b',
            field=models.IntegerField(default=0, verbose_name='points_b'),
        ),
        migrations.AddField(
            model_name='qwestions',
            name='point_c',
            field=models.IntegerField(default=0, verbose_name='points_c'),
        ),
        migrations.AddField(
            model_name='qwestions',
            name='point_d',
            field=models.IntegerField(default=0, verbose_name='points_d'),
        ),
        migrations.AlterField(
            model_name='comingrequests',
            name='members',
            field=models.CharField(choices=[('1', '1 участник'), ('2', '2 участника'), ('3', '3 участника'), ('4', '4 участника'), ('5', '5 участников'), ('6', '6 участников'), ('7', '7 участников'), ('8', '8 участников'), ('9', '9 участников'), ('10', '10 участников')], max_length=16, verbose_name='количество участников'),
        ),
    ]
